### ISSUE TITLE
wrong value

### ISSUE THREAD

**Issue by lazo86** [nightshift2k/freqtrade-strategies#2]
https://github.com/nightshift2k/freqtrade-strategies/blob/0d4b9501729bebe8e57473882a5c28bd99525e7e/CombinedBinHAndClucHyperStrategy.py#L124

hello, here a small copy paste error, expected value should be buy_bin_bbdelta_close   :)

**Comment by nightshift2k** [comment]
strategy has been replaced, so it is not relevant anymore :)
